#! /bin/sh
### BEGIN INIT INFO
# Provides:          toggle_light
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/pi/SwitchLED
DAEMON_NAME=toggle_light
DAEMON=$DIR/$DAEMON_NAME.py

# Add any command line options for your daemon here
DAEMON_OPTS=""
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

start() {
    nohup python $DAEMON &
    echo "$DAEMON_NAME Service started."
}
 
stop() {
    pid=`ps -ef | grep 'python /home/pi/SwitchLED/toggle' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $DAEMON {start|stop|restart}"
    exit 1
esac
exit 0